/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Finger */

#ifndef _Included_Finger
#define _Included_Finger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Finger
 * Method:    initFiveFingerManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Finger_initFiveFingerManager
  (JNIEnv *, jobject);

/*
 * Class:     Finger
 * Method:    setPositionTarget
 * Signature: (ID)C
 */
JNIEXPORT jchar JNICALL Java_Finger_setPositionTarget
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     Finger
 * Method:    setSpeed
 * Signature: (ID)C
 */
JNIEXPORT jchar JNICALL Java_Finger_setSpeed
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     Finger
 * Method:    setMaxNewton
 * Signature: (ID)C
 */
JNIEXPORT jchar JNICALL Java_Finger_setMaxNewton
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     Finger
 * Method:    getmA
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_Finger_getmA
  (JNIEnv *, jobject, jint);

/*
 * Class:     Finger
 * Method:    getNewton
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_Finger_getNewton
  (JNIEnv *, jobject, jint);

/*
 * Class:     Finger
 * Method:    getPosition
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_Finger_getPosition
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
